# Site settings
title: ROS Index
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a community-maintained index of robotics software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rosindex.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rosindex
destination: _deploy

# Build settings
markdown: redcarpet
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: rouge

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis
    - with_toc_data
    - html_toc
    - tables

# OLD from jekyll 2.x
#highlighter: pygments

# If true, this begins with an existing db
use_db_cache: false
db_cache_filename: _caches/_deploy_cache.db
report_filename: _caches/_deploy_index_report.yaml
report_diff_filename: _caches/_deploy_index_report_diff.yaml
debbuild_release_path: _caches/debbuild_releases
wiki_title_index_filename: _caches/ros_org_wiki_title_index.txt

# If true, this skips finding repos based on the repo sources
skip_discover: false
# If true, this skips updating the known repos
skip_update: false
# If true, this skips scraping the cloned repos
skip_scrape: false
# If true, this skips generating the search index
skip_search_index: false

checkout_threads: 4
checkout_path: "../checkout"

# if non-empty, only scrape these packages (useful for debugging / partial db updates)
repo_name_whitelist: []
# if non-empty, only scrape these repo ids (useful for debugging / partial db updates)
repo_id_whitelist: []

# domains which are broken
domain_blacklist:
  - 'kforge.ros.org'
  - 'code.in.tum.de'
  #- 'devel.iri.upc.edu'

exclude:
  - _scripts
  - _deploy
  - _devel
  - _caches
  - _rosdistro
  - _rosforks
  - _deploy_cache.db
  - _devel_cace.db
  - _ruby_libs
  - _checkout
  - node_modules
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md

rosdistro_path: _rosdistro
repos_path: _rosforks/repos
attic_file: _rosforks/attic.yaml
index_old_doc_paths: false

# ROS distros to look for
#
# Distros are given big buttons and "old" distros are relegated to share a
# drop-down list in the distro selector.
#
distros:
  - 'kinetic'
  - 'jade'
  - 'indigo'
  - 'hydro'
old_distros:
  - 'groovy'
  - 'fuerte'
  - 'electric'
  - 'diamondback'

# rosdep / xylem platforms
#
# This is a list of platforms and versions found in the rosdep database if a
# platform / version key isn't found here, then it will throw and error and
# should either be added or fixed if it was erroneous.
#
# Each key under 'versions' is a map from version identifier to version
# display name. If the display name is empty, then the capitalized version of
# the identifier will be used.
#
platforms:
  arch:
    name: 'Arch Linux'
    versions: {}
  centos:
    name: 'CentOS'
    versions: {}
  cygwin:
    name: 'Cygwin'
    versions: {}
  debian:
    name: 'Debian'
    versions:
      sarge: ""
      etch: ""
      lenny: ""
      squeeze: ""
      wheezy: ""
      jessie: ""
      sid: "Sid (Unstable)"
  fedora:
    name: 'Fedora'
    versions:
      beefy: "17 (Beefy Miracle)"
      spherical: "18 (Spherical Cow)"
      "schrödinger’s": "19 (Schrödinger's Cat)"
      heisenbug: "20 (Heisenberg)"
      '21': "Fedora 21"
      '22': "Fedora 22"
  freebsd:
    name: 'FreeBSD'
    versions: {}
  gentoo:
    name: 'Gentoo Linux'
    versions: {}
  mandrake:
    name: 'Mandrake/Mandriva Linux'
    versions: {}
  opensuse:
    name: 'openSUSE'
    versions: {}
  osx:
    name: 'Mac OS X'
    versions:
      leopard: ""
      snow: "Snow Leopard"
      lion: ""
      "mountain lion": ""
      mavericks: ""
      yosemite: ""
  rhel:
    name: 'Red Hat Enterprise Linux'
    versions: {}
  ubuntu:
    name: 'Ubuntu'
    versions:
      karmic: ""
      lucid: ""
      maverick: ""
      natty: ""
      oneiric: ""
      precise: ""
      quantal: ""
      raring: ""
      saucy: ""
      trusty: ""
      trusty_python3: "Trusty (Python3)"
      utopic: ""
      utopic_python3: "Utopic (Python3)"
      vivid: ""
      vivid_python3: "Vivid (Python3)"
      wily: ""
      wily_python3: "Wily (Python3)"
      xenial: ""
      xenial_python3: "Xenial (Python3)"

# These are the names of available package managers across all the
# platforms
package_manager_names:
  apt: ['ubuntu','debian']
  gem: []
  homebrew: ['osx']
  macports: ['osx']
  pacman: ['arch']
  pip: []
  portage: ['gentoo']

# package list page
packages_per_page: 50
repos_per_page: 50

# uncomment the following line for testing (limit the number of indexed repos)
max_repos: 2
